package licensetext

import "testing"

const protobufLicense = `Copyright 2008 Google Inc.  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
    * Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED.

Code generated by the Protocol Buffer compiler is owned by the owner
of the input file used when generating it.  This code is not
standalone and requires a support library to be linked with it.  This
support library is itself covered by the above license.`

const mitWithPreamble = `The Awesome Project — Licensing Terms

This project is made available to you under the following terms.

MIT License

Copyright (c) 2019 Some Company GmbH

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.`

const iscLicense = `ISC License

Copyright (c) 2020, Jane Doe

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES.`

const zeroBSD = `Copyright (C) 2006 by Rob Landley <rob@landley.net>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES.`

const bsd2 = `Copyright (c) 2015 Foo. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS "AS IS".`

const apache2Header = `                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.`

const gpl2OrLater = `    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.`

const lgpl21Only = `                  GNU LESSER GENERAL PUBLIC LICENSE
                       Version 2.1, February 1999

 Copyright (C) 1991, 1999 Free Software Foundation, Inc.
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.`

const mpl2 = `Mozilla Public License Version 2.0
==================================

1. Definitions
--------------

1.1. "Contributor"
    means each individual or legal entity that creates, contributes to
    the creation of, or owns Covered Software.`

const unlicense = `This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.`

const dualMITApache = `This project is dual-licensed.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files, to deal in the Software
without restriction.

                                 Apache License
                           Version 2.0, January 2004`

func TestDetect(t *testing.T) {
	tests := []struct {
		name string
		text string
		want string
	}{
		{"protobuf BSD-3 with trailing preamble", protobufLicense, "BSD-3-Clause"},
		{"MIT with corporate preamble", mitWithPreamble, "MIT"},
		{"ISC", iscLicense, "ISC"},
		{"0BSD", zeroBSD, "0BSD"},
		{"BSD-2", bsd2, "BSD-2-Clause"},
		{"Apache-2.0", apache2Header, "Apache-2.0"},
		{"GPL-2.0-or-later", gpl2OrLater, "GPL-2.0-or-later"},
		{"LGPL-2.1-only", lgpl21Only, "LGPL-2.1-only"},
		{"MPL-2.0", mpl2, "MPL-2.0"},
		{"Unlicense", unlicense, "Unlicense"},
		{"dual MIT OR Apache", dualMITApache, "Apache-2.0 OR MIT"},
		{"empty", "", ""},
		{"too short", "MIT", ""},
		{"unrelated text", "This document describes how to build the project on Linux and macOS. See CONTRIBUTING.md for details about the review process and coding style.", ""},
		{"proprietary EULA", "END-USER LICENSE AGREEMENT. This software is licensed, not sold. You may not reverse engineer, decompile, or disassemble the software. All rights reserved by the vendor.", ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := Detect(tt.text); got != tt.want {
				t.Errorf("Detect() = %q, want %q", got, tt.want)
			}
		})
	}
}
